//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoputerShop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Changelogs
    {
        public int id_changelog { get; set; }
        public int changelog_user_id { get; set; }
        public string changelog_message { get; set; }
        public System.DateTime changelog_date { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
