//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoputerShop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells
    {
        public int id_sell { get; set; }
        public int sell_order_id { get; set; }
        public int sell_product_id { get; set; }
        public int sell_product_count { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
